---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: deny-all-authz-ns
spec:
  {} 
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-peerauth
  namespace: default
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: igaupolicy
 namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
  - issuer: "https://idp-on-cloud-run-3kdezruzua-uc.a.run.app"
    audiences:
    - "https://foo.bar"
    - "https://svc1.example.com"
    - "https://svc2.example.com"       
    jwksUri: "https://idp-on-cloud-run-3kdezruzua-uc.a.run.app/certs" 
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: igazpolicy
 namespace: istio-system
spec:
 selector:
   matchLabels:
     app: istio-ingressgateway
 rules:
 - to:
   - operation:
       methods: ["GET"]
   when:
   - key: request.auth.claims[iss]
     values: ["https://idp-on-cloud-run-3kdezruzua-uc.a.run.app"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: svc1-au
spec:
  selector:
    matchLabels:
      app: svc1
  jwtRules:
  - issuer: "https://idp-on-cloud-run-3kdezruzua-uc.a.run.app"
    audiences:
    - "https://svc1.example.com"
    jwksUri: "https://idp-on-cloud-run-3kdezruzua-uc.a.run.app/certs" 
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: svc1-az
spec:
 action: ALLOW    
 selector:
   matchLabels:
     app: svc1
 rules:
 - to:
   - operation:
       methods: ["GET"]
   when:
   - key: request.auth.claims[iss]
     values: ["https://idp-on-cloud-run-3kdezruzua-uc.a.run.app"]
   - key: request.auth.claims[aud]
     values: ["https://svc1.example.com"]       
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: svc2-au
spec:
  selector:
    matchLabels:
      app: svc2
  jwtRules:
  - issuer: "https://idp-on-cloud-run-3kdezruzua-uc.a.run.app"
    audiences:
    - "https://svc2.example.com"
    jwksUri: "https://idp-on-cloud-run-3kdezruzua-uc.a.run.app/certs" 
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: svc2-az
spec:
 action: ALLOW  
 selector:
   matchLabels:
     app: svc2
 rules:
 - to:
   - operation:
       methods: ["GET"]  
  #  from:
  #  - source:
  #      principals: ["cluster.local/ns/default/sa/svc1-sa"] 
   when:
   - key: request.auth.claims[iss]
     values: ["https://idp-on-cloud-run-3kdezruzua-uc.a.run.app"]
   - key: request.auth.claims[aud]
     values: ["https://svc2.example.com"]
  # - key: request.auth.claims[groups]
  #   values: ["group1", "group2"]
   - key: request.auth.claims[sub]
     values: ["bob"]
